### ISSUE TITLE
isup.me only works for HTTP links

### ISSUE THREAD

**Issue by Smile4ever** [Albirew/resurrect-pages-isup-edition#5]
The isup.me provider only works for HTTP links and not HTTPS links. This can be solved by omitting "https://" from the URL that you pass to isup.me.

**Comment by Albirew** [comment]
Juste tried with github with and without https, both works but since page content is the same, I can't see if.https cached pages differs than the ones with http.
I need to find an archived website with a different landing page when going with http or https to see if cached page are different or not.

**Comment by Smile4ever** [comment]
for example:
resurrect http://isup.me/https://github.com/Albirew/resurrect-pages/issues/5 becomes http://isup.me/https://github.com/Albirew/resurrect-pages/issues/5

which shows:
 Huh? http://https doesn't look like a site on the interwho.

**Comment by Albirew** [comment]
my bad, i've readed archive.org instead of isup.me.
